# Config file for Big Watermelon Web Scraper Discord Bot

---
# Images to ignore
# The bot will not make a post with these images
ignoreList:
  - 

# URL to scrape from
url: 

# CSS selector to get images from
selector: 